package main

import (
	"database/sql"
	"fmt"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	_ "github.com/mattn/go-sqlite3"
	"menumemory-backend/db"
	"net/http"
	"os"
)

// Visit struct to represent visit data
type Visit struct {
	ID           string // Visit ID
	UserID       string // User ID
	Date         string // Visit date
	Time         string // Visit time
	RestaurantID int    // Associated restaurant ID
}

var q *db.Queries

func SetupApp() *gin.Engine {
	fmt.Println("Beginning Database Initialization")
	db_, err := sql.Open("sqlite3", "warehouse.db")
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
	q = db.New(db_)
	fmt.Println("Finished Database Initialization")

	r := gin.Default()

	// Allow all cors origins
	r.Use(cors.Default())

	r.StaticFile("/openapi.json", "./openapi.json")
	r.StaticFile("/openapi.yaml", "./openapi.yaml")

	r.GET("/ping", func(c *gin.Context) {
		c.String(200, "Pong Uwu")
	})

	r.GET("/restaurants", func(c *gin.Context) {
		searchTerm := c.Query("search_term")
		if searchTerm == "" {
			c.JSON(http.StatusBadRequest, gin.H{"error": "search_term is required"})
			return
		}

		restaurants, err := q.GetRestaurantsLike(c, "%"+searchTerm+"%")
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"restaurants": restaurants,
		})
	})

	// Add the PUT endpoint for updating visits
	r.PUT("/visits/:visit_id", func(c *gin.Context) {
		visitID := c.Param("visit_id")
		userID := c.Query("user_id")

		if userID == "" {
			c.JSON(http.StatusBadRequest, gin.H{"error": "user_id is required"})
			return
		}

		var req struct {
			Date         string `json:"date" binding:"required"`
			Time         string `json:"time" binding:"required"`
			RestaurantID int    `json:"restaurant_id" binding:"required"`
		}

		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request body"})
			return
		}

		// Check if the visit belongs to the user
		visit, err := getVisitByID(c, visitID)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch visit"})
			return
		}
		if visit == nil || visit.UserID != userID {
			c.JSON(http.StatusForbidden, gin.H{"error": "Unauthorized"})
			return
		}

		// Update the visit in the database
		err = updateVisitInDB(c, visitID, req.Date, req.Time, req.RestaurantID)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to update visit"})
			return
		}

		c.JSON(http.StatusOK, gin.H{"message": "visit updated successfully"})
	})

	return r
}

func main() {
	r := SetupApp()
	r.Run() // listen and serve on 0.0.0.0:8080
}

// getVisitByID retrieves a visit by its ID
func getVisitByID(c *gin.Context, visitID string) (*Visit, error) {
	// Fetch the visit using the query generated by sqlc
	visit, err := q.GetVisitByID(c, visitID)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil // No visit found
		}
		return nil, err
	}

	// Map the visit from the query result to our Visit struct
	return &Visit{
		ID:           visit.ID,
		UserID:       visit.UserID,
		Date:         visit.Date,
		Time:         visit.Time,
		RestaurantID: visit.RestaurantID,
	}, nil
}

// updateVisitInDB updates the visit details in the database
func updateVisitInDB(c *gin.Context, visitID, date, time string, restaurantID int) error {
	// Use the generated query to update the visit details
	err := q.UpdateVisit(c, db.UpdateVisitParams{
		ID:           visitID,
		Date:         date,
		Time:         time,
		RestaurantID: restaurantID,
	})
	return err
}
